#!/bin/bash

set -eu

for svc in "tidb-master" "tidb-4.0"; do
    killall -v -1 $svc 2>/dev/null || continue
    sleep 1 # give some grace shutdown period
    killall -v -9 $svc &>/dev/null || continue
done
sleep 1 # give some time for the OS to reap all processes
lsof -n -P -i :4001 -i :10081 -i :4002 -i :10082 || true
